### ISSUE TITLE
Update to Mojo 24.6?

### ISSUE THREAD

**Issue by general-rishkin** [endia-ai/Endia#3]
First, this is a great library and a service to the community.

I would like to know if you are still working on this library and hope to keep maintaining it? I only ask because the last activity was 3 months ago and it has not been updated to Mojo 24.6 yet.

**Comment by TilliFe** [comment]
Hi there, thanks for reaching out. Yes i am still working on it. I plan to update to the new version in the next 2 weeks. Unfortunately, I am having a ton of Uni related things to do at the moment, which forces me work less on Endia as I would like to. Stay tuned! :)

**Comment by general-rishkin** [comment]
Excellent! Glad to hear you are still working on it. I will wait patiently for the next release.
